name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch num squared
        id: get_square
        uses: ./  # 수정: # Uses an action in the root directory -> 빈 줄 추가
        with: 
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"  # 수정: 앞뒤로 공백 추가
